---
- include: create_certificate.yml
- include: install_apache.yml
- include: install_mysql.yml
- include: install_php.yml
- include: install_phpunit.yml
- include: install_xdebug.yml
- include: install_composer.yml
